name: "🛠 General Update"
description: "기능 추가, 수정, 리팩토링 등 특정 범주에 포함되지 않는 변경 사항을 정리합니다."
title: "[Update] "
labels: ["update", "refactor", "misc"]
assignees:
  - ""  # 자동으로 지정할 담당자 (필요하면 추가)
body:
  - type: textarea
    attributes:
      label: 📝 변경 내용
      description: 어떤 변경을 할 것인지 설명해주세요.
      placeholder: 예) API 응답 형식 변경, 코드 리팩토링, 성능 최적화 등
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🎯 변경 목적
      description: 변경이 필요한 이유를 설명해주세요.
      placeholder: 예) 성능 최적화, 유지보수 용이성 향상, 보안 강화 등
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 변경할 작업을 체크박스 형태로 작성해주세요.
      placeholder: |
        - [ ] API 응답 포맷 개선
        - [ ] 코드 리팩토링
        - [ ] 불필요한 로직 제거
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 💻 적용 대상
      description: 변경 사항이 적용될 범위를 선택해주세요.
      options:
        - 전체 프로젝트
        - 백엔드 (API)
        - 프론트엔드 (UI)
        - 데이터베이스
        - 기타 (설명 추가)
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📌 참고 사항
      description: 변경과 관련된 추가 정보가 있다면 작성해주세요.
    validations:
      required: false
